# Generated by Django 5.0.6 on 2024-05-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='parent_post',
            new_name='parent_comment',
        ),
    ]
